compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

npmAuthToken: "${NPM_DIFUKS_TOKEN-}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.com/"

yarnPath: .yarn/releases/yarn-4.2.1.cjs
